# NumPy

Forked from [Parallel Machine Learning with scikit-learn and IPython](https://github.com/ogrisel/parallel_ml_tutorial) by Olivier Grisel

- NumPy arrays, dtype, and shape
- Commmon array operations
- Reshape and update in-place
- Combine arrays
- Create sample data

In [2]:
import numpy as np

## NumPy arrays, dtype, and shape

In [3]:
a = np.array([1, 2, 3])
print(a)
print(a.shape)
print(a.dtype)

[1 2 3]
(3,)
int32


In [4]:
b = np.array([[0, 2, 4], [1, 3, 5]])
print(b)
print(b.shape)
print(b.dtype)

[[0 2 4]
 [1 3 5]]
(2, 3)
int32


In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones(shape=(3, 4), dtype=np.int32)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

## Common array operations

In [7]:
c = b * 0.5
print(c)
print(c.shape)
print(c.dtype)

[[0.  1.  2. ]
 [0.5 1.5 2.5]]
(2, 3)
float64


In [9]:
d = a + c
print(d)

[[1.  3.  5. ]
 [1.5 3.5 5.5]]


In [10]:
d[0]

array([1., 3., 5.])

In [11]:
d[0, 0]

1.0

In [12]:
d[:, 0]

array([1. , 1.5])

In [13]:
d.sum()

19.5

In [14]:
d.mean()

3.25

In [15]:
d.sum(axis=0)

array([ 2.5,  6.5, 10.5])

In [16]:
d.mean(axis=1)

array([3. , 3.5])

## Reshape and update in-place

In [19]:
e = np.arange(12)
print(e)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [21]:
f = e.reshape(3, 4)
print(f)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [22]:
e[5:] = 0
print(e)

[0 1 2 3 4 0 0 0 0 0 0 0]


In [23]:
f

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

f.flags

## Combine arrays

In [25]:
a

array([1, 2, 3])

In [26]:
b

array([[0, 2, 4],
       [1, 3, 5]])

In [27]:
d

array([[1. , 3. , 5. ],
       [1.5, 3.5, 5.5]])

In [28]:
np.concatenate([a, a, a])

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [29]:
np.vstack([a, b, d])

array([[1. , 2. , 3. ],
       [0. , 2. , 4. ],
       [1. , 3. , 5. ],
       [1. , 3. , 5. ],
       [1.5, 3.5, 5.5]])

In [30]:
np.hstack([b, d])

array([[0. , 2. , 4. , 1. , 3. , 5. ],
       [1. , 3. , 5. , 1.5, 3.5, 5.5]])